/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecompensesRouteImport } from './routes/recompenses'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'

const RecompensesRoute = RecompensesRouteImport.update({
  id: '/recompenses',
  path: '/recompenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/parents': typeof ParentsRoute
  '/recompenses': typeof RecompensesRoute
  '/demo/prisma': typeof DemoPrismaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/parents': typeof ParentsRoute
  '/recompenses': typeof RecompensesRoute
  '/demo/prisma': typeof DemoPrismaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/parents': typeof ParentsRoute
  '/recompenses': typeof RecompensesRoute
  '/demo/prisma': typeof DemoPrismaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/parents' | '/recompenses' | '/demo/prisma'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/parents' | '/recompenses' | '/demo/prisma'
  id: '__root__' | '/' | '/about' | '/parents' | '/recompenses' | '/demo/prisma'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ParentsRoute: typeof ParentsRoute
  RecompensesRoute: typeof RecompensesRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recompenses': {
      id: '/recompenses'
      path: '/recompenses'
      fullPath: '/recompenses'
      preLoaderRoute: typeof RecompensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ParentsRoute: ParentsRoute,
  RecompensesRoute: RecompensesRoute,
  DemoPrismaRoute: DemoPrismaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
